language: python
python:
- '3.7'
script: true
before_deploy:
- cd code/mapeathor/
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: __token__
  password:
    secure: "WqCIizMBGNIpnTJq/RtufnX4mI2e6MPjtgZEJS6bjIGP57isNoaUQPQkLVx3L8uXAWBunBpZkNqptmlrZttC3BIXeEEsMq4wH1gIGPDQrBoUdU3HRI1Hlz9JSeYmKF7zAu9fAC3Sdd/n+rjQgb0SrhZkXTvsyrznZnVEmAi2hCcD71jN9Ano7BqlooHuVFX28LlCD8bEFgnIy6gAPov/ZKpr+jS6pbM1V7thcyMpETvi+cmldUv+4zCIVFKpl5xRgXSi9DK2qVu6O8QGQxCC6V7UXEfsbFOsSh6xdjUGIilhPgJSKXfQScIAHqUT+k5iN8+fEcuBsdYYJmVhDQ7hXX6eJQEVQzO85U/+Sc4ZjH5qINH/C1Gl0PcipYof7C9kRMTEd5BTbjIj3sj/vC3K34ShC49Crlcd5ROJyYW7+x1n2jD24ID1fZrT+2lUOGpfsj/rM8x5d6avBqnPt/X/d2EFGpaN2Qmix+VUad7tcyrUVAjtPEURo4d2ptVdU4mwZtXohwt1NJVjvpxPFOZ/RL0E3LA95DeumC9r42mM7qCCwQSdrswH9QibosB+jVgJuY1351EYOW/QG2cjelBYnHBsw0B2Fs9o9H5hKe89MLYJK6tUw3CWiZGN36/MEA3m2fcNQQMtsxPMqo9lVavHeA/eSS5CHvfIW38FF+Nt0Qo="
