language: python
python:
- '3.7'
script: true
before_deploy:
- cd src/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  password:
    secure: "O29kM7sNHERtJ2sM8QAZPaZBvE3sA/rzt4LygW/ua50DKwRQOlaGOzgWgBf5DIN+Nme0sk66tmG0bo4wKMyI0XeeqZVZxjmM2/gK5Zatau7L3PHWcs/OwwcQI675scHpfuS5Fypj28UchKmTpJvXmxWKJsqGaEKqsPvVhzcG9YTd76NuFARUyGWdUn5pVELD6N2B6hlFQzAx7lH82iJyEAxyKdYtFLNwjUBLyWvH76hHZH9NC8M6z7D+Y3J1CKNFZ6McTaLtNNfKpGAKehTc4oVykAd8bUn5+E3HUXX60+OBN2UAhlXwE7tVr4M78QHtqAA2yC8Fdqxe/2GMLaQaMXe7w7FFVLMczW1gn867RtVn6chWCJLpxj9RcqNtghv7X49SAescD4dyHcOjMWxcEnzy5JG0sGPF7TsnC/L6tlW/NM5WqmL04H1MOaLK+WSMYnNmeM7nEwhObEWHOcRj3sj79xOzUTSNZ/GZX6IMrqrDgjnX+PniTMpB5f4ijP4laOB1UHaqYzYEhyLHupe2fQzX/dvONd4skjUzr6KFSyVurIMh2UV2DZ1oT0cWTd1KZK5UpEiFvCwK3NRjyGiW6jgvOj+sD5crWApdAq68yrkt0n6q8GM3JB3BvmTvBPTr5MVvaPA2Pn/D8yobX9BwPXUxWunstS7V4T1jPiwC9tI="
