language: python
python:
- '3.7'
script: true
before_deploy:
- cd code/mapeathor/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  password:
    secure: NOK9mcPkaZWqrhiaj28RO+JkhDe3NhYOKIkUMcEHAV7xw9JWR3Ordus4SdRsNqRIYKxYAMeZsvIuo+42dxkbEiwzKxftj+rB2B8uI5sgGuOmEw6ulnFIYMbwQVVBYGg2oIizk4EgCxEEYH5grpu1P6xAVdhIiDQUTZDA/mMzMv6mPVG3kevxohfay94KXsy+aj0gCFWEPaY19V3c+0B3bT6KzwW3YqOSLwGyFuWpYuf+lRUR+maU+F/R37Q1VKB9cqEg3YFZ4R+xcvf0yOTJePOFO0vF5RsI1ydDs5kdhzuLURyvfhyYjWUD5bXN9QET8LjY7SlaBx2LRLLEOWuCyXJqY1g5i7kclzCE0FURX99sfLnPEKB4DCfkxKH0hqPerDgH6XYfSsl8AbrLg6Ae2jigqg8YarFkrwFmsWRHM0Iu6sXWS/+deyYtUbbVYxlsZjwQP/GoP743UXm9rdm741PeM+4guh5GIXiyvGIoB5KrnqNP3EVzr3yg5GUEouWIcakKy857oPwm2xnmmxoRVkIu0dYPye3uXPAh8mfiv+M+ZgZZQOW+mfgUaAD3GwDa8O9qd7RdIOxnjEYnmsnb4ozZVDKXOrdoPCc5qxJTfUVcLfaSecvBKY5FmVFHiQRgqaGiiKpdVcZ+GcsOm/SSv/1Cp+mk6g8x2Af2KX6DAfE=
