language: python
python:
- '3.7'
script: true
before_deploy:
- cd code/mapeathor/
deploy:
  provider: pypi
  user: __token__
  password:
    secure: YxvfkQ+kypCXRwb2V8RqpAGNSd+5BlW2bb4UB5HBvSk1fSc7XhoIQp7VmhGtXQZRIfcQBNdYUsVUBorjnGH4ccBDfa+nTxnLFxOQyRT6cUJc2Z1yBnoVz7Tc+n7tVCj4OmNgIeNB2fad/S8T4IZjHy6m/kn8/k++GIjwVpLpbAqQEczSYbvi3YpFirOhjDI50CPpKfoIyNHxHSno0hG41bQooW/HOdh963uIm5wSrjWdtnBuyLsfgKwWcTkR3ucx1CGkVDtjoDlByL1OWxCBwfh3thhaawN4qsWlCtAO6HDZT0OdF7lxxVljXw/QNqGBZZsAr+h5kcgbihS7ls5lgM2Gc9lYc9PPyj/GzCs2wtssywB7elq0tsyJMjmxLzHqGkEZa89etv5/rGKbcBgAi8Y9aO6IV/6WJj/oHbglYvCO1WPmpq4OXzcOQSHB7zE3wLMwWCVIetpe0OpT7yATKo2QYKmYtSIdcIXidJIY3ec0p2UfIgvKuhDJOojSutO1wOURIx2hQAtPl0WNEjllkQYfpuwLCCe7CnM0yfC1NjtQbWxEk4klc1yri8V5poVA7hFmq+WgNX95oZMq9TWC9yHZwxXVcCPQlZQ6ZfVUwtEdtv4YRjF9R9rTk4xNzeaxNpPvjee4HXiuQpoLRJ3t4fUdYQ+2Hfu71xq9rA+5PNY=
