language: python
python:
- '3.7'
script: true
before_deploy:
- cd code/mapeathor/
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: "__token__"
  password:
    secure: "GydUXfz6p5sBOOQZWSUVjo4KZI0PDVcMVNatmDXSkDbVssWCctbcWROykwHPUBYAGIoVlm1MX4ZFCQRF7LJHm6MhXSpxKNQ5C83GEHhz76G3Ed7fWGQ6sKUgfwKHCFxiXX+X03ucqX5gLinsO3WUkMGpzCqmJdU+Bdi9NxwubhV9NEbQMr+f8hsmdl6jkkZBSmpVkKwvo3XpIU5LXA6IISfkgGcJJcnNiu5N3CqbmIWNb7I0fyoy1c8wJLrWjZzI6ApCfsipvFuWOP18E7Ebbo+sGH2GZzmBZjQTwT7PchBEHMyKxh9w8Es1j0SC3JucbvexpD9tUHbdbzvVfrwS8gId/qHCi03jZG8PMYPQU4NYpMUsDVTGGRp5sjJ18PB7AOG6bpZPR1h5+bkiPs1wBA/7CNigJjSbQ7Cp4UYTAOLu10+7KHZwm9bhHXA9RTqIVtGBVjlhNeM1O/YxGIEPrxu/CksUQOJ/wNxSDizjdRO8Tvr2OStaI+zx+PXQV4qdmOw7ZQ1MzRteC6qvurekwr/I1Wmih7oldUAm7i5XuJowobALeNW/Zc3ch7BgUD/CJj4XaNXCDwaLgU5boOP0GLNJrxFM76qTW25ZBguqK3oJgP5LooE0LVux3KId/br1g8j7mfMHT3GvdTpfQkyNKD+UK5bftKVBFHcvBd0nxeA="
