language: python
python:
- '3.7'
script: true
before_deploy:
- cd code/mapeathor/
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ZdFrfFxTELIGCGdT2Ni+92wERaijyYvSzjhKaOQmrASmLObX86tQIrZVsuyuLP1WGJchamL51SdmNCoUWfbhlqrxKokKD//SJi774XtuPul8D5+N6OBIyoubTiAAo3GxUZLtjvymHV5pNmmqFUbY7GZ4ziUbSlfGmBr+S/BgLiqBT6y+thzJPrIY31/BPlmrF+C7D3JT1xjkXraRweLlyBgV/qAAKwHOT1z8Hl7slmuBR5HlGBsnDtcLEmblKjQ4IsEkjbddxY3CV4QJCz+euTYGtELClsCtam2ArGOtON+AZt8+Yw/DcM7VrEk+4rqX6U9dYAPZ//0URiH/Ucv3O/AzMtL0+W9QAy/OR6uguhsFlXFwLLEMEciAnOf5oxN8PYQaLSVfUS7RS6ZU32Y33ZO5iuz7njMXWqNyEbSk12TnpHr3h7s/2eXYYJamYDYLBKk3Qs/4xHTKIMD233hKnUVS2jxH8gAt81IaWjYV7NS+gZIFvCtWhQc5jb1ToD88WZZkphEB4e6FStbggha5u3p7mICVRg56Y5GsQ2wnEvN4c/2pJ2Bq3o0z9AhBTgW7dyKUcOvdRKXybwpVpJ2n9tMf20U5BWtiCubiRYhZCi4kZ4xjj3pPVm893Te0bf0QxXydxLAFWXuBnLb2q9M7CvJBF0oJXeeeLqA6OkdGCR8=
